name          'chriscowley-gitlab'
version       '0.1.0'
source        'https://github.com/chriscowley/chriscowley-gitlab.git'
author        'chriscowley'
license       'Apache 2.0'
summary       'Install Gitlab on CentOS'
description   'Install Gitlab on CentOS'
project_page  'https://github.com/chriscowley/chriscowley-gitlab'

dependency 'puppetlabs/stdlib'
